quotes_app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField


class SearchForm(FlaskForm):
    query = StringField('Search')
    schsubmit = SubmitField('Go')

quotes_app/main/routes.py
from flask import render_template, request, flash, Blueprint, redirect, url_for
from flask_login import current_user
from quotes_app.models import Post, Like
from quotes_app.main.utils import (prepare_posts_display, get_best_posts,
            get_trending, update_like_table, is_valid_page, prepare_posts,
            prepare_num_pages)
from quotes_app.main.forms import SearchForm
from quotes_app.config import PER_PAGE, BEST_TREND


main = Blueprint('main', __name__)


@main.route("/", methods=['GET', 'POST'])
@main.route("/home", methods=['GET', 'POST'])
def home():
    schform = SearchForm()
    page = request.args.get('page', 1, type=int)
    sort = request.args.get('srt', 'n', type=str)
    if schform.schsubmit.data and schform.validate_on_submit():
        if schform.query.data != '':
            return redirect(url_for('main.home', sch=schform.query.data))
        else:
            return redirect(url_for('main.home', page=page, srt=sort))
    post_id = request.args.get('star', type=int)
    search = request.args.get('sch', type=str)
    if post_id:
        if current_user.is_authenticated:
            update_like_table(current_user, post_id)
        else:
            flash('Please log in to give a star.', 'info')
        if search:
            return redirect(url_for('main.home', page=page, sch=search, srt=sort))
        else:
            return redirect(url_for('main.home', page=page, srt=sort))
    posts = prepare_posts(search, sort)
    num_pages = prepare_num_pages(posts, page, PER_PAGE)
    posts_data = prepare_posts_display(posts[(page-1)*PER_PAGE:page*PER_PAGE], 10)
    best_posts = get_best_posts(BEST_TREND)
    trend_posts = get_trending(BEST_TREND)
    if search:
        schform.query.data = search
    return render_template('main/home.html', posts_data=posts_data, num_pages=num_pages, 
        schform=schform, best_posts=best_posts, trend_posts=trend_posts, page=page,
        search=search, sort=sort)


@main.route("/about", methods=['GET', 'POST'])
def about():
    schform = SearchForm()
    if schform.schsubmit.data and schform.validate_on_submit():
        if schform.query.data != '':
            return redirect(url_for('main.home', sch=schform.query.data))
        else:
            return redirect(url_for('main.about'))
    return render_template('main/about.html', schform=schform)


@main.route("/terms", methods=['GET', 'POST'])
def terms():
    schform = SearchForm()
    if schform.schsubmit.data and schform.validate_on_submit():
        if schform.query.data != '':
            return redirect(url_for('main.home', sch=schform.query.data))
        else:
            return redirect(url_for('main.terms'))
    return render_template('main/terms.html', schform=schform)

quotes_app/users/routes.py
# db.engine.table_names() to list all table names in db.
# MoreInfoUser.__table__.create(db.session.bind) to add the MoreInfoUser table
# to the existing db.

from flask import (Blueprint, render_template, redirect, flash, request, url_for,
                    Markup)
from flask_login import login_user, logout_user, current_user, login_required
from quotes_app import db, bcrypt
from quotes_app.models import User, Post, Like, Comment, MoreInfoUser, LikeComment
from quotes_app.users.forms import (RegistrationForm, LoginForm, ResetRequestForm,
                                ResetPasswordForm, UpdateProfileForm)
from quotes_app.users.utils import (send_reset_token, get_best_posts_user,
                                get_recent_stars_user, get_posts_num_plc,
                                save_picture, remove_picture)
from quotes_app.main.utils import prepare_posts_display, update_like_table
from quotes_app.main.forms import SearchForm
from quotes_app.config import PER_PAGE, BEST_TREND
from datetime import datetime as dt


users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    schform = SearchForm()
    if schform.schsubmit.data and schform.validate_on_submit():
        if schform.query.data != '':
            return redirect(url_for('main.home', sch=schform.query.data))
        else:
            return redirect(url_for('users.register'))
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.submit.data and form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data,
            password=hashed_password)
        db.session.add(user)
        db.session.commit() # can i do this in one commit?
        user = User.query.filter_by(username=form.username.data).first()
        about_user = MoreInfoUser(full_name=form.username.data, info_author=user)
        db.session.add(about_user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'info')
        return redirect(url_for('users.login'))
    return render_template('users/register.html', title='Sign Up', form=form, schform=schform)

@users.route("/login", methods=['GET', 'POST'])
def login():
    schform = SearchForm()
    if schform.schsubmit.data and schform.validate_on_submit():
        if schform.query.data != '':
            return redirect(url_for('main.home', sch=schform.query.data))
        else:
            return redirect(url_for('users.login'))
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))    
    form = LoginForm()
    if form.submit.data and form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessfull. Please check email or password', 'info')
    return render_template('users/login.html', title='Sign In', form=form, schform=schform)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/user/<string:username>", methods=['GET', 'POST'])
@login_required
def user_profile(username):
    schform = SearchForm()
    page = request.args.get('page', 1, type=int)
    if schform.schsubmit.data and schform.validate_on_submit():
        if schform.query.data != '':
            return redirect(url_for('main.home', sch=schform.query.data))
        else:
            return redirect(url_for('users.user_profile', username=username, page=page))
    post_id = request.args.get('star', type=int)
    user = User.query.filter_by(username=username).first_or_404()
    if post_id:
        update_like_table(current_user, post_id)
        return redirect(url_for('users.user_profile', username=username, page=page))
    about_user = MoreInfoUser.query.filter_by(info_author=user).first()
    posts, num_posts, num_likes, num_comments = get_posts_num_plc(user)
    posts = posts.paginate(page=page, per_page=PER_PAGE)
    posts_data = prepare_posts_display(posts.items, 10)
    best_posts = get_best_posts_user(user, BEST_TREND)
    recent_stars = get_recent_stars_user(user, BEST_TREND)
    background_image = url_for('static',
        filename='background_pics/' + about_user.background_pic)
    return render_template('users/user_profile.html', title=username, posts=posts,
        posts_data=posts_data, schform=schform, user=user, about_user=about_user,
        background_image=background_image, num_posts=num_posts,
        num_likes=num_likes, num_comments=num_comments, best_posts=best_posts,
        recent_stars=recent_stars)

@users.route("/user/<string:username>/update", methods=['GET', 'POST'])
@login_required
def update_profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    if user != current_user:
        flash("You can't update this profile.", 'info')
        return redirect(url_for('main.home'))
    schform = SearchForm()
    if schform.schsubmit.data and schform.validate_on_submit():
        if schform.query.data != '':
            return redirect(url_for('main.home', sch=schform.query.data))
        else:
            return redirect(url_for('users.update_profile', username=username))
    form = UpdateProfileForm()
    about_user = MoreInfoUser.query.filter_by(info_author=user).first()
    if form.submit.data and form.validate_on_submit():
        # when error occurs during saving/removing pics,
        # filenames in db records can be wrong
        if form.profile_pic.data:
            profile_pic_file = save_picture(form.profile_pic.data, 1)
            remove_picture(current_user.image_file, 1)
            current_user.image_file = profile_pic_file
        if form.background_pic.data:
            background_pic_file = save_picture(form.background_pic.data, 2)
            remove_picture(about_user.background_pic, 2)
            about_user.background_pic = background_pic_file
        current_user.username = form.username.data
        current_user.email = form.email.data 
        about_user.full_name = form.full_name.data
        about_user.city = form.city.data
        about = form.about.data.strip(' \n  ,')
        about_user.about = Markup(about.replace('\n', '<br>'))
        about_user.last_update = dt.utcnow()
        db.session.commit()
        flash('Your account has been updated!', 'info')
        return redirect(url_for('users.user_profile', username=current_user.username))
    elif request.method == 'GET':
        form.username.data = user.username
        form.email.data = user.email
        form.full_name.data = about_user.full_name
        form.city.data = about_user.city
        form.about.data = about_user.about.replace('<br>', '\n')
    _, num_posts, num_likes, num_comments = get_posts_num_plc(user)
    background_image = url_for('static',
        filename='background_pics/' + about_user.background_pic)
    return render_template('users/update_profile.html', user=user, title='Update Profile',
        about_user=about_user, background_image=background_image, schform=schform,
        form=form, num_posts=num_posts, num_likes=num_likes, num_comments=num_comments)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    schform = SearchForm()
    if schform.schsubmit.data and schform.validate_on_submit():
        if schform.query.data != '':
            return redirect(url_for('main.home', sch=schform.query.data))
        else:
            return redirect(url_for('users.reset_request'))
    form = ResetRequestForm()
    if form.submit.data and form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_token(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('users/reset_request.html', title='Reset Password Reqeust', form=form,
        schform=schform)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    schform = SearchForm()
    if schform.schsubmit.data and schform.validate_on_submit():
        if schform.query.data != '':
            return redirect(url_for('main.home', sch=schform.query.data))
        else:
            return redirect(url_for('users.reset_password', token=token))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token!', 'info')
        redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.submit.data and form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'info')
        return redirect(url_for('users.login'))
    return render_template('users/reset_token.html', title='Reset Password', form=form,
        schform=schform)

quotes_app/templates/main/about.html
{% extends "main/layout.html" %}
{% block content %}
<div class="col-lg-8 mx-auto">
    <div class="bg-white shadow rounded overflow-hidden">
        <div class="container d-flex justify-content-center no-about px-5">
            <img src="{{ url_for('static', filename='icons_photos/bulb.png') }}" class="img-fluid">
        </div>
        <div class="container d-flex justify-content-center text-center no-about mb-5">
            <h2 class="not-found-color"><b>We work on this. Available soon</b></h2>
        </div>
    </div>
</div>
{% endblock content %}

quotes_app/templates/main/home.html
{% extends "main/layout.html" %}
{% block content %}
<div class="col-md-8">
    <div class="mx-auto">
        <div class="container py-4 px-4 mb-4 bg-white shadow rounded overflow-hidden">
            <div class="card rounded card-nf bg-white p-0">
                <div class="card-body p-0">
                    <div class="d-flex flex-wrap">
                        <div class="ml-1 mr-auto">
                            <div class="dropdown">
                                <button class="btn btn-filter btn-order p-0 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <img src="{{ url_for('static', filename='icons_photos/filter.png') }}" width="40" height="40">
                                </button>
                                <div class="dropdown-menu m-0" aria-labelledby="dropdownMenuButton">
                                    {% if search %}
                                        <a href="{{ url_for('main.home', sch=search, srt='n') }}" class="btn btn-drop-grey btn-order" role="button" aria-pressed="true">New</a>
                                        <a href="{{ url_for('main.home', sch=search, srt='t') }}" class="btn btn-drop-grey btn-order" role="button" aria-pressed="true">Top</a>
                                        <a href="{{ url_for('main.home', sch=search, srt='tr') }}" class="btn btn-drop-grey btn-order" role="button" aria-pressed="true">Trending</a>
                                    {% else %}
                                        <a href="{{ url_for('main.home', srt='n') }}" class="btn btn-drop-grey btn-order" role="button" aria-pressed="true">New</a>
                                        <a href="{{ url_for('main.home', srt='t') }}" class="btn btn-drop-grey btn-order" role="button" aria-pressed="true">Top</a>
                                        <a href="{{ url_for('main.home', srt='tr') }}" class="btn btn-drop-grey btn-order" role="button" aria-pressed="true">Trending</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="ml-auto">
                            <a href="{{ url_for('posts.new_post') }}" class="btn btn-lg btn-order btn-violet m-0" role="button" aria-pressed="true">New Adage</a>
                        </div>
                    </div> 
                </div>
            </div>
            {% for post in posts_data %}
                <div class="card rounded shadow bg-light py-2 mb-5">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12 link-post-content">
                                <a href="{{ url_for('posts.post', post_id=post[-2].id) }}"><h3 class="card-title "><b>"{{ post[-2].content | safe }}"</b></h3></a>
                            </div>
                            <div class="col-12 d-flex justify-content-end text-center">
                                <h6><i>{{ post[-2].author }}</i></h6>
                            </div>
                            <div class="col mt-2">
                                <h6 class="card-subtitle mb-2 text-muted">
                                    <p class="card-text text-muted small"> Posted by <a href="{{ url_for('users.user_profile', username=post[-2].posted_by.username) }}" class="font-weight-bold text-dark"> {{ post[-2].posted_by.username }}</a> on {{ post[-2].date_posted.strftime('%-d %a, %Y') }}</p>
                                </h6>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer bg-white p-1">
                        <div class="row">
                            <div class="col-md-auto ">
                                <a href="{{ url_for('posts.post', post_id=post[-2].id) }}" class="btn btn-outlined btn-black text-muted bg-transparent p-1 ml-1 mr-2" data-wow-delay="0.7s">
                                    <img src="{{ url_for('static', filename='icons_photos/comment.png') }}" class="mr-1 " width="19" height="19">
                                    <small>COMMENT</small>
                                </a>
                                <span class="vl mr-2 ml-0"></span>
                                {% if search %}
                                    <a href="{{ url_for('main.home', page=page, star=post[-2].id, sch=search, srt=sort) }}" class="btn btn-outlined btn-black text-muted bg-transparent p-1 ml-2 mr-0" data-wow-delay="0.7s"></a>
                                {% else %}
                                    <a href="{{ url_for('main.home', page=page, star=post[-2].id, srt=sort) }}" class="btn btn-outlined btn-black text-muted bg-transparent p-1 ml-2 mr-0" data-wow-delay="0.7s">
                                {% endif %}
                                {% if post[-1] == True %}
                                    <img src="{{ url_for('static', filename='icons_photos/christmas-star.png') }}" width="19" height="19">
                                {% else %}
                                    <img src="{{ url_for('static', filename='icons_photos/star.png') }}" width="19" height="19">
                                {% endif %}
                                </a>
                                <small>STARS</small>
                            </div>
                            <div class="col-md-auto">
                                <ul class="list-inline mb-0">
                                    {% for user in post[:-2] %}
                                    <li class="list-inline-item">
                                        <a href="{{ url_for('users.user_profile', username=user.username) }}">
                                            <img src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}" alt="DP" class=" rounded-circle" width="35" height="35">
                                        </a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <div class="container d-flex justify-content-center">
                {% for page_num in num_pages %}
                    {% if page_num %}
                        {% if page == page_num %}
                            {% if search %}
                                <a class="mr-1 mb-4 btn btn-violet" href="{{ url_for('main.home', page=page_num, sch=search, srt=sort) }}">{{ page_num }}</a>
                            {% else %}
                                <a class="mr-1 mb-4 btn btn-violet" href="{{ url_for('main.home', page=page_num, srt=sort) }}">{{ page_num }}</a>
                            {% endif %}
                        {% else %}
                            {% if search %}
                                <a class="mr-1 mb-4 btn btn-outline-violet" href="{{ url_for('main.home', page=page_num, sch=search, srt=sort) }}">{{ page_num }}</a>
                            {% else %}
                                <a class="mr-1 mb-4 btn btn-outline-violet" href="{{ url_for('main.home', page=page_num, srt=sort) }}">{{ page_num }}</a>
                            {% endif %}
                        {% endif %}
                    {% else %}
                        ...
                    {% endif %}
                {% endfor %}
            </div>
            {% if not posts_data %}
                <div class="container d-flex justify-content-center no-matching">
                    <img src="{{ url_for('static', filename='icons_photos/no_results.png') }}" class="img-fluid">
                </div>
                <div class="container d-flex justify-content-center text-center no-matching mb-5">
                    <h2 class="no-matching-color"><b>No matching results. Try later</b></h2>
                </div>
            {% endif %}
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="content-section shadow">
        <div class="mb-3 text-center">
            <h3>Best List</h3>
        </div>
        <ul class="list-group">
            {% if not best_posts %}
                <a href="{{ url_for('posts.new_post') }}"><li class="list-group-item list-group-item-light">No Adages. Add one.</li></a>
            {% else %}
                {% for post in best_posts %}
                    <a href="{{ url_for('posts.post', post_id=post.id) }}" class="p-1"><li class="list-group-item list-group-item-light">"{{ post.content | safe }}"</li></a>
                {% endfor %}
            {% endif %}
        </ul>
    </div>
    <div class="content-section shadow">
        <div class="mb-3 text-center">
            <h3>Trending</h3>
        </div>
        <ul class="list-group">
            {% if not trend_posts %}
            <a href="{{ url_for('posts.new_post') }}"><li class="list-group-item list-group-item-light">No activity. Add an Adage or give a star.</li></a>
            {% else %}
                {% for post in trend_posts %}
                <a href="{{ url_for('posts.post', post_id=post.id) }}" class="p-1"><li class="list-group-item list-group-item-light">"{{ post.content | safe }}"</li></a>
                {% endfor %}
            {% endif %}
        </ul>
    </div>
</div>
{% endblock content %}

quotes_app/templates/main/layout.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">

        {% if title %}
            <title>SageSAY: {{ title }}</title>
        {% else %}
            <title>SageSAY: the widest adages community</title>
        {% endif %}

    </head>
    <body>
        <div class="content">
            <div class="navbar navbar-expand-md navbar-dark bg-violet fixed-top">
                <div class="container-fluid">
                    <div class="justify-content-between navbar-helper justify-content-center">
                        <div>
                            <a class="navbar-brand" href="{{ url_for('main.home') }}">SageSAY</a>
                        </div>
                        <div class="nav-form w-100 pr-2">
                            <form method="POST" action="">
                                <div class="input-group">
                                        {{ schform.hidden_tag() }}
                                        <div class="search-field">
                                            {{ schform.schsubmit() }}
                                        </div>
                                        {{ schform.query(class="form-control pl-1 pr-0", placeholder=schform.query.label.text) }}
                                </div>
                            </form>
                        </div>
                        <div>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                        </div>
                    </div>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <div class="navbar-nav">
                            {% if current_user.is_authenticated %}
                                <a class="nav-item nav-link" href="{{ url_for('users.user_profile', username=current_user.username) }}">Account</a>
                                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                            {% else %}
                                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div role="main" class="container mt-80 align-items-stretch">
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        {% with messages = get_flashed_messages(with_categories=true) %}
                            {% if messages %}
                                {% for category, message in messages %}
                                    <div class="alert alert-{{ category }}">
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        {% endwith %}
                    </div>
                </div>
                <div class="row justify-content-center">
                    {% block content %}{% endblock content %}
                </div>
            </div>
        </div>
        <footer class="footer"><h6 class="mx-auto">All rights reserved. &#169; 2021 by SageSAY Inc.</h6></footer>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>